---
 # Exercise for setting up a web server in an EC2
- name: Exercise for setting up a web server in an EC2
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
  - setup